### PR TITLE
z-merge.yml

### PR DESCRIPTION
**Pull request by godban**
Support backsyncs from v1

### CODE REVIEW

**Review by nitzanashi — COMMENTED** [review]
should be z-backmerge.yml
```
branches:
    - v1

**Review by nitzanashi — APPROVED** [review]

**Review by dobladov — APPROVED** [review]

**Comment by godban** [comment]
@z-merge it

**Comment by dobladov** [comment]
> @z-merge it

We don't have fancy bots here.

**Comment by godban** [comment]
@z-merge it

**Comment by godban** [comment]
@dobladov now we do

**Pull request merged**
